### ISSUE TITLE
A business coop offer.

### ISSUE THREAD

**Issue by erdemcagatay1** [Wazarr94/Wazarr94.github.io#1]
@Wazarr94  , we would like to speak with you about developing an html5 game for our startup. We have just opened this account to get in touch with you.  If you are interested, in my next comment i will write our e-mail adress . Thank you.

**Comment by Wazarr94** [comment]
Hello, this project is not for commercial use.

You may use it as an inspiration, but it's only meant to be for educational purposes.
Thanks for understanding.
