### ISSUE TITLE
about ur v4 script

### ISSUE THREAD

**Issue by nas0s** [Wazarr94/Wazarr94.github.io#3]
sorry about this issue bcs it doesn't belong to this project but I wanted to get your thoughts on this. I'm using ur level_4 bot since 2 years and thank you so much for this but as with every software project, updating is required. You wrote in the readme file that an update will come in 2021, but I guess it wasn't possible. Do you have an update plan in your future plans?

**Comment by Wazarr94** [comment]
hello, I'm working on other projects but I'll see if I have time to release a more updated version in the next weeks. No promises

**Comment by nas0s** [comment]
Thanks for the answer. I'm sure you'll do a great job if you take the time.
